packages:
  - contract
  - sdk

overrides:
  smoldot: npm:@aspect-build/empty@0.0.0
  '@midnight-ntwrk/ledger-v8': 8.1.0
  '@midnight-ntwrk/onchain-runtime-v3': 3.0.0

allowBuilds:
  '@swc/core': true
  classic-level: true
  esbuild: true
  msgpackr-extract: true
