import { Buildings, Check, Key, Plus, ShieldCheck, UserPlus, UsersThree } from '@phosphor-icons/react';
import { useState } from 'react';
import { Button } from '../components/Button';
import { Modal } from '../components/Modal';
import { PrivacyBadge } from '../components/PrivacyBadge';
import { shortHash } from '../lib/encoding';
import { formatDate, initials } from '../lib/format';
import { useAppStore } from '../store/AppStore';
import type { MemberRole } from '../types';

export const WorkspacesPage = () => {
  const { state, actions } = useAppStore();
  const [createOpen, setCreateOpen] = useState(false);
  const [inviteOpen, setInviteOpen] = useState(false);
  const [credentialOpen, setCredentialOpen] = useState(false);
  const [name, setName] = useState('');
  const [description, setDescription] = useState('');
  const [memberName, setMemberName] = useState('');
  const [wallet, setWallet] = useState('');
  const [veilId, setVeilId] = useState('');
  const [role, setRole] = useState<MemberRole>('member');
  const [department, setDepartment] = useState('Engineering');
  const [credentialSubjectId, setCredentialSubjectId] = useState('alice');
  const [credentialRole, setCredentialRole] = useState('Member');
  const [busy, setBusy] = useState(false);
  const [formError, setFormError] = useState('');
  const [workspaceId, setWorkspaceId] = useState(state.workspaces[0]?.id ?? '');
  const workspace = state.workspaces.find((item) => item.id === workspaceId) ?? state.workspaces[0];
  const workspaceMembers = state.members.filter((member) => workspace?.memberIds.includes(member.id) ?? true);
  const workspaceCredentials = state.credentials.filter((credential) => workspace?.memberIds.includes(credential.subjectId) ?? true);

  return (
    <section className="page workspace-page">
      <header className="page-heading"><div><span className="eyebrow">Private teams</span><h1>{workspace?.name ?? 'Workspaces'}</h1><p>{workspace?.description ?? 'Organize encrypted work around roles and credentials.'}</p>{state.workspaces.length > 1 && <select className="select workspace-switcher" value={workspace?.id} onChange={(event) => setWorkspaceId(event.target.value)}>{state.workspaces.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>}</div><div className="heading-actions"><Button tone="secondary" onClick={() => setCreateOpen(true)}><Plus size={16} /> New workspace</Button><Button tone="primary" onClick={() => setInviteOpen(true)}><UserPlus size={17} /> Invite member</Button></div></header>
      {workspace && <div className="workspace-overview"><div><Buildings size={28} weight="thin" /><span><small>Workspace</small><strong>{workspace.name}</strong></span></div><div><UsersThree size={28} weight="thin" /><span><small>Members</small><strong>{workspace.memberIds.length} active</strong></span></div><div><ShieldCheck size={28} weight="thin" /><span><small>Privacy</small><PrivacyBadge level={workspace.privacy} /></span></div><div><Key size={28} weight="thin" /><span><small>Access model</small><strong>Role + credential</strong></span></div></div>}

      <div className="workspace-grid">
        <section className="members-panel"><header><div><span className="overline">Directory</span><h2>Members and roles</h2></div><button onClick={() => { setCredentialSubjectId(workspaceMembers[0]?.id ?? ''); setFormError(''); setCredentialOpen(true); }}>Issue credential</button></header><div className="member-list">{workspaceMembers.map((member) => <article key={member.id}><span className="member-avatar">{initials(member.name)}</span><div><strong>{member.name}</strong><small>{member.wallet}</small>{member.veilId && <small>Veil ID · {shortHash(member.veilId, 6, 4)}</small>}</div><span>{member.department}</span><select className="select" value={member.role} onChange={(event) => actions.updateMember(member.id, { role: event.target.value as MemberRole })} disabled={member.id === 'alice'}><option value="owner">Owner</option><option value="admin">Admin</option><option value="manager">Manager</option><option value="member">Member</option><option value="guest">Guest</option></select><i className={`member-status member-status--${member.status}`}>{member.status}</i></article>)}</div></section>
        <aside className="credential-panel"><span className="overline">Private credentials</span><h2 className="serif">Prove the role. Hide the record.</h2><p>Workspace credentials let a member satisfy file policies without revealing the whole credential.</p><div className="credential-stack">{workspaceCredentials.map((credential) => <article key={credential.id}><header><span><ShieldCheck size={17} weight="light" />{credential.status}</span><code>{shortHash(credential.commitment, 5, 4)}</code></header><strong>{credential.subjectName}</strong><p>{credential.organization} · {credential.department} · {credential.role}</p><small>Expires {formatDate(credential.expiresAt)}</small></article>)}</div></aside>
      </div>

      <Modal open={createOpen} onClose={() => setCreateOpen(false)} title="Create a private workspace"><form className="simple-form" onSubmit={(event) => { event.preventDefault(); const created = actions.addWorkspace(name, description); setWorkspaceId(created.id); setCreateOpen(false); setName(''); setDescription(''); }}><label className="field"><span>Name</span><input className="input" value={name} onChange={(event) => setName(event.target.value)} /></label><label className="field"><span>Description</span><textarea className="textarea" value={description} onChange={(event) => setDescription(event.target.value)} /></label><footer className="modal-actions"><Button tone="primary" disabled={!name.trim()}>Create workspace</Button></footer></form></Modal>
      <Modal open={inviteOpen} onClose={() => setInviteOpen(false)} title="Invite a wallet"><form className="simple-form" onSubmit={(event) => { event.preventDefault(); actions.addMember({ name: memberName.trim(), wallet: wallet.trim(), veilId: veilId.trim().replace(/^0x/, '') || undefined, role, department: department.trim(), status: 'invited' }, workspace?.id); setInviteOpen(false); setMemberName(''); setWallet(''); setVeilId(''); }}><label className="field"><span>Name</span><input className="input" value={memberName} onChange={(event) => setMemberName(event.target.value)} /></label><label className="field"><span>Midnight wallet</span><input className="input" value={wallet} onChange={(event) => setWallet(event.target.value)} placeholder="mn_addr_preprod1…" /></label><label className="field"><span>Veil ID</span><input className="input" value={veilId} onChange={(event) => setVeilId(event.target.value)} placeholder="Copy the 64-character identity from Settings" spellCheck={false} /></label><p className="field-hint">The Veil ID binds private grants and credentials to the member.</p><div className="form-split"><label className="field"><span>Role</span><select className="select" value={role} onChange={(event) => setRole(event.target.value as MemberRole)}><option value="admin">Admin</option><option value="manager">Manager</option><option value="member">Member</option><option value="guest">Guest</option></select></label><label className="field"><span>Department</span><input className="input" value={department} onChange={(event) => setDepartment(event.target.value)} /></label></div><footer className="modal-actions"><Button tone="primary" disabled={!memberName.trim() || !wallet.trim() || !/^(?:0x)?[0-9a-f]{64}$/i.test(veilId.trim())}>Send private invite</Button></footer></form></Modal>
      <Modal open={credentialOpen} onClose={() => setCredentialOpen(false)} title="Issue an organization credential"><form className="simple-form" onSubmit={async (event) => { event.preventDefault(); const subject = workspaceMembers.find((member) => member.id === credentialSubjectId); if (!subject) return; setBusy(true); setFormError(''); try { await actions.issueCredential({ subjectId: subject.id, subjectName: subject.name, issuer: workspace?.name ?? 'VeilDrive', organization: workspace?.name ?? 'VeilDrive', department: department.trim(), role: credentialRole.trim(), status: 'active', expiresAt: new Date(Date.now() + 365 * 86_400_000).toISOString() }); setCredentialOpen(false); } catch (error) { setFormError(error instanceof Error ? error.message : 'Credential issuance failed.'); } finally { setBusy(false); } }}><label className="field"><span>Member</span><select className="select" value={credentialSubjectId} onChange={(event) => setCredentialSubjectId(event.target.value)}>{workspaceMembers.map((member) => <option key={member.id} value={member.id}>{member.name}</option>)}</select></label><div className="form-split"><label className="field"><span>Department</span><input className="input" value={department} onChange={(event) => setDepartment(event.target.value)} /></label><label className="field"><span>Role claim</span><input className="input" value={credentialRole} onChange={(event) => setCredentialRole(event.target.value)} /></label></div><p><Check size={14} /> Only the credential commitment is registered. Claim values remain in the holder’s private state.</p>{formError && <p className="form-error" role="alert">{formError}</p>}<footer className="modal-actions"><Button tone="primary" disabled={busy || workspaceMembers.length === 0 || !credentialRole.trim()}>{busy ? 'Issuing on preprod…' : 'Issue credential'}</Button></footer></form></Modal>
    </section>
  );
};
